### ISSUE TITLE
No Objects in samsung.0 created

### ISSUE THREAD

**Issue by OneCreek** [iobroker-community-adapters/ioBroker.samsung#117]
**Describe the bug**  
No Samsung Objects in samsung.0

**To Reproduce**  
1. Install latest Samsung Adapter via Expert Mode -> GitHub Source 0.5.11 on 14.06.2022 (see below: additional context)
2. Add Instance from Adapter tab
![2022-06-14 21_45_05-add instances - iobroker](https://user-images.githubusercontent.com/107502675/173676608-2aa9723f-e694-4cff-b888-b9d366b5e534.png)
3. Create PIN for Samsung 2015
4. Enter PIN in Instance -> works

**Expected behavior**  
In Objects there is not only Samsung.Admin, but also _Samsung.0_
under _system.adapter.samsung.0_ there are some entries, but nothing like before under _Samsung.0_ like _volume up_, ...

**Screenshots & Logfiles**  
![2022-06-14 21_04_54-logs - iobroker](https://user-images.githubusercontent.com/107502675/173675267-17910f3a-23d3-4a4f-bcc7-503e5252d140.png)

If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 0.5.11
 - JS-Controller version: host: 4.0.23
 - Admin: v5.3.8
 - NPM: 6.14.17
 - Node version: v14.19.3
 - Plattform: docker
 - OS: linux
 - Architectur: arm
 - Device: Raspberrry ARMv7 Processor rev 3 (v7l)
 - TV: UE55ju6850 (2015)

**Additional context**  
during adapter install there are some warnings:
![2022-06-14 21_42_35-adapters install- iobroker](https://user-images.githubusercontent.com/107502675/173676332-be8fa7de-8980-4b89-b9eb-33e5d06c37fb.png)

**Comment by OneCreek** [comment]
Update: if I start the Instance before I configure my individual settings (IP, MAC), the Objects are being created!

**Comment by Apollon77** [comment]
Please post a debg log as text and not graphics ... 
technically after "Connection to TV initialised" there should be at least one more logline ...

**Comment by OneCreek** [comment]
sorry about the gaphics.
There is nothing coming after the "Connection to TV initialised". Just restarted the Instance and waited.

**Comment by OneCreek** [comment]
can I help with some more information somehow?

**Comment by OneCreek** [comment]
I still get the message/Log: and it stopps after saying initialising...
I could gather/enter the PIN from the TV in the step before...

samsung.0	2022-11-01 11:00:33.493	info	Connection to TV initialised
samsung.0	2022-11-01 11:00:33.491	debug	resp is init2 all is done
samsung.0	2022-11-01 11:00:33.419	debug	Initializing HJ lib
samsung.0	2022-11-01 11:00:33.348	info	starting. Version 0.5.11 in /opt/iobroker/node_modules/iobroker.samsung, node: v16.16.0, js-controller: 4.0.23
samsung.0	2022-11-01 11:00:32.606	debug	Plugin sentry Initialize Plugin (enabled=true)
samsung.0	2022-11-01 11:00:32.360	debug	States connected to redis: 127.0.0.1:9000
samsung.0	2022-11-01 11:00:32.270	debug	States create User PubSub Client
samsung.0	2022-11-01 11:00:32.267	debug	States create System PubSub Client
samsung.0	2022-11-01 11:00:32.220	debug	Redis States: Use Redis connection: 127.0.0.1:9000
samsung.0	2022-11-01 11:00:32.119	debug	Objects connected to redis: 127.0.0.1:9001
samsung.0	2022-11-01 11:00:32.106	debug	Objects client initialize lua scripts
samsung.0	2022-11-01 11:00:31.899	debug	Objects create User PubSub Client
samsung.0	2022-11-01 11:00:31.897	debug	Objects create System PubSub Client
samsung.0	2022-11-01 11:00:31.879	debug	Objects client ready ... initialize now
samsung.0	2022-11-01 11:00:31.765	debug	Redis Objects: Use Redis connection: 127.0.0.1:9001
samsung.0	2022-11-01 11:00:25.231	info	Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
samsung.0	2022-11-01 11:00:25.229	info	terminating
samsung.0	2022-11-01 11:00:25.227	info	Got terminate signal TERMINATE_YOURSELF
