### ISSUE TITLE
WARN deprecated core-js@1.2.7: core-js@<3.23.3

### ISSUE THREAD

**Issue by OneCreek** [iobroker-community-adapters/ioBroker.samsung#129]
When installing the latest Adapter 0.5.11 via NMP I get the following message with warnings:

  $ iobroker url iobroker.samsung --host iobroker --debug
  install iobroker.samsung
  NPM version: 8.11.0
  Installing iobroker.samsung... (System call)
  npm WARN deprecated appium-logger@2.1.0: Moved into appium-support
  npm WARN deprecated core-js@1.2.7: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
  npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
  added 30 packages in 21s99 packages are looking for funding run `npm fund` for details
  upload [1] samsung.admin /opt/iobroker/node_modules/iobroker.samsung/admin/index.html index.html text/html
  upload [0] samsung.admin /opt/iobroker/node_modules/iobroker.samsung/admin/samsung.png samsung.png image/png
  Process exited with code 0

**Comment by gidhap** [comment]
same here :( will an installation harm the iobroker stability? pls advise. Txs

**Comment by Feuer-sturm** [comment]
@gidhap I am running the version 0.5.11 on my production system and have no impact

**Comment by gidhap** [comment]
@Feuer-sturm txs ! Did you make your Samsung TV work and if so would you min sharing the settings?
I am running out of options, none of them worked with my QLED :(

**Comment by Feuer-sturm** [comment]
@gidhap I have an old Samsung TV D-Series (UE45D8000). This are my settings
![grafik](https://user-images.githubusercontent.com/25422320/205369870-d156785b-b2ae-410e-9af1-54a50d9d5c08.png)

**Comment by Apollon77** [comment]
it are just infos from npm ... ignore them
