### ISSUE TITLE
V 0.6.0 funktioniert mit Samsung HJ Series nicht mehr.

### ISSUE THREAD

**Issue by marian-t-web-de** [iobroker-community-adapters/ioBroker.samsung#202]
**Describe the bug**  
wie in Issue #201 geschildert, funktioniert der <ioBroker.samsung-community> Adapter v. 0.5.0 nach einem Update vom js-controller auf Version 6.0.9 nicht mehr. Die Ursache ist, dass dieser nicht mehr weiterentwickelt wird und dass dies durch die Verschiebung in die Repository <ioBroker.samsung> vom Iobroker heraus nicht erkennbar ist. Das o.g. Issue wurde auf gefixt gesetzt, weit der ioBroker.samsung Adapter v. 0.6.0 unter js-controller v. 6.0.9 nicht mehr crasht.
Allerdings funktioniert dieser mit Tizen HJ-TV's auch nicht - die Anmerkung in Github "...HJ Series tested by me on UE55HU7200." bezieht sich nur auf die (funktionierende) Version 0.5.0 des Ursprungsadapters  <ioBroker.samsung-community>.
Bei der Bearbeitung des o.g. issues hat sich herausgestellt das die aktuelle Version mangels HJ-TV als Testgerät ungetestet ausgeliefert wurde.

**To Reproduce**  
1. Installiere und starte ioBroker.samsung Adapter/Instanz
2. Prüfe im Log die Meldungen der Instanz: "device connected" erscheint nicht meht
3. Prüfe das auf die Statepoints keine Interaktion folgt - eine Fehlfunktion.

**Expected behavior**  
<oBroker.samsung> Adapter/Instanz v. 0.6.0 verbindet sich mit HJ-TV so wie das vorher der Fall bei <oBroker.samsung-community> Adapter v. 0.5.0 war

**Screenshots & Logfiles**  
Beim debug von <oBroker.samsung> Module v. 0.6.0.
node --inspect-brk=<IP>:9229 /opt/iobroker/node_modules/iobroker.samsung/main.js --force --logs --trace-warnings
ist über chrome://inspect folgendes Protokoll einsehbar (s.u.). M.E. es deutet daraufhin, dass der Pfad zu 'encoding' module in requireStack-array nicht vorhanden ist. 
Siehe: "err: Error: Cannot find module 'encoding' Require stack: ..."

Bei meiner Installation sind die En-/Decryption Scripts unter /opt/iobroker/node_modules/iobroker.samsung/lib/H-and-J-Series-lib/Pairing/Encryption zu finden. 
Ansonsten unter /opt/iobroker/node_modules/iobroker.samsung/node_modules/node-fetch/lib sind nur ein  paar index.js(?)

Sofern dass der (und der einzige) Fehler ist und jemand über die Fähigkeit verfügt, das zu bereinigen könnte man den Adapter für HJ-TV's wieder heilen. 

`Local
Exception
: 
Error: Cannot find module 'encoding' Require stack: - /opt/iobroker/node_modules/iobroker.samsung/node_modules/node-fetch/lib/index.js - /opt/iobroker/node_modules/iobroker.samsung/lib/H-and-J-Series-lib/SamsungTv.js - /opt/iobroker/node_modules/iobroker.samsung/main.js at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15) at Module._load (node:internal/modules/cjs/loader:975:27) at Module.require (node:internal/modules/cjs/loader:1225:19) at require (node:internal/modules/helpers:177:18) at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.samsung/node_modules/node-fetch/lib/index.js:163:12) at Module._compile (node:internal/modules/cjs/loader:1356:14) at Module._extensions..js (node:internal/modules/cjs/loader:1414:10) at Module.load (node:internal/modules/cjs/loader:1197:32) at Module._load (node:internal/modules/cjs/loader:1013:12) at Module.require (node:internal/modules/cjs/loader:1225:19)
this
: 
ƒ Module(id = '', parent)
err
: 
Error: Cannot find module 'encoding' Require stack: - /opt/iobroker/node_modules/iobroker.samsung/node_modules/node-fetch/lib/index.js - /opt/iobroker/node_modules/iobroker.samsung/lib/H-and-J-Series-lib/SamsungTv.js - /opt/iobroker/node_modules/iobroker.samsung/main.js at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15) at Module._load (node:internal/modules/cjs/loader:975:27) at Module.require (node:internal/modules/cjs/loader:1225:19) at require (node:internal/modules/helpers:177:18) at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.samsung/node_modules/node-fetch/lib/index.js:163:12) at Module._compile (node:internal/modules/cjs/loader:1356:14) at Module._extensions..js (node:internal/modules/cjs/loader:1414:10) at Module.load (node:internal/modules/cjs/loader:1197:32) at Module._load (node:internal/modules/cjs/loader:1013:12) at Module.require (node:internal/modules/cjs/loader:1225:19)
filename
: 
false
isMain
: 
false
message
: 
"Cannot find module 'encoding'\nRequire stack:\n- /opt/iobroker/node_modules/iobroker.samsung/node_modules/node-fetch/lib/index.js\n- /opt/iobroker/node_modules/iobroker.samsung/lib/H-and-J-Series-lib/SamsungTv.js\n- /opt/iobroker/node_modules/iobroker.samsung/main.js"
options
: 
undefined
parent
: 
Module {id: '/opt/iobroker/node_modules/iobroker.samsung/node_modules/node-fetch/lib/index.js', path: '/opt/iobroker/node_modules/iobroker.samsung/node_modules/node-fetch/lib', exports: {…}, filename: '/opt/iobroker/node_modules/iobroker.samsung/node_modules/node-fetch/lib/index.js', loaded: false, …}
parentPath
: 
"/opt/iobroker/node_modules/iobroker.samsung/node_modules/node-fetch/lib/index.js"
paths
: 
Array(9)
0
: 
"/opt/iobroker/node_modules/iobroker.samsung/node_modules/node-fetch/lib/node_modules"
1
: 
"/opt/iobroker/node_modules/iobroker.samsung/node_modules/node-fetch/node_modules"
2
: 
"/opt/iobroker/node_modules/iobroker.samsung/node_modules"
3
: 
"/opt/iobroker/node_modules"
4
: 
"/opt/node_modules"
5
: 
"/node_modules"
6
: 
"/root/.node_modules"
7
: 
"/root/.node_libraries"
8
: 
"/usr/lib/node"
length
: 
9
[[Prototype]]
: 
Array(0)
request
: 
"encoding"
requireStack
: 
Array(3)
0
: 
"/opt/iobroker/node_modules/iobroker.samsung/node_modules/node-fetch/lib/index.js"
1
: 
"/opt/iobroker/node_modules/iobroker.samsung/lib/H-and-J-Series-lib/SamsungTv.js"
2
: 
"/opt/iobroker/node_modules/iobroker.samsung/main.js"
length
: 
3`

**Versions:**  
 - Adapter version: <0.6.0>
 - JS-Controller version: <6.0.9>
 - Node version: <18.20.4>
 - Operating system: <Raspi-os/Debian>

**Additional context**  
Ich unterstütze natürlich - soweit möglich - die Tests der bereinigten Version des Adapters, bzw. die Suche nach weiteren Fehler.

**Comment by mcm1957** [comment]
Es gibt nur einen Adapter. Der Adapter ioBroker.samsung-community wurde im Jänner 2022 (!) in ioBroker.samsung (zurück) umbenannt. Die Codebasis wurde dabei weder kopiert noch geforked. Siehe GitHub commit history - es ist EIN Adaptercode seit Beginn an.

Die Aussage dass der Adapter ioBroker.Samsung-community nicht mehr weiterentwickelt wird / wurde ist daher streng genommen unrichtig. V0.6.0 IST die aktuelle Weiterentwicklung des Adapters.

Das ändert aber natürlich nichts daran, dass er zusammen mit einem Gerät / einer Geräteserie nicht mehr funktioniert. Leider ist nicht klar ab wann das Problem aufgetreten ist.

Danke jedenfalls mal für as klare Issue incl. Log das bei einer Fehlersuche sicher hilfreich sein wird.

**Comment by marian-t-web-de** [comment]
Danke für den Hinweis auf das Forum, habe schon Betrag verfasst.
Mein TV ist Samsug UE55JS8590TXZG BJ. 2016/Modell 2015 mit Tizen OS, daher habe ich (einige Jahre) die API-Type SamsungHJ erfolgreich benutzt. Der <ioBroker.samsung-community> Adapter v. 0.5.0 war in der einer Version noch vor kurzem in Github zu finden und ist nach wie vor der Einzige, der mit meinem TV funktioniert. Habe ich noch letzte Woche <ioBroker.samsung> v.0.6.0 parallel dazu installiert. Deren Historie beginnt mit 0.5.1, wäre das der gleiche Adapter müsste doch mit 0.5.0 (oder früher) anfangen?
Unter Docker und js-adapter 5.0.19 funktioniert der alte noch, in einer zweiten Installation crasht (siehe #201). Der neue endet bei Initialisierung, "connected" -Meldung kommt nicht meht (auch #201).

**Comment by marian-t-web-de** [comment]
Ich schrieb am 19.08. folgendes:
> ...Habe ich noch letzte Woche <ioBroker.samsung> v.0.6.0 parallel dazu installiert. Deren Historie beginnt mit 0.5.1, wäre das der gleiche Adapter müsste doch mit 0.5.0 (oder früher) anfangen? ...

@mcm1957 Wo sind die Versionen bis einschließlich 0.5.0 zu finden?

**Comment by mcm1957** [comment]
Das Repo ist unverändert ioBroker.samsung. Der Adapter wurde nur zwischenzeitlich auf samsung-community umbenannt und dann wieder retour. Siehe GitHub changelog

**Comment by marian-t-web-de** [comment]
Dass die Repo unverändert sei hast du schon vorher geschrieben. 
Die Frage war wo finde ich die mit SamsungHJ API funktionierende v. 0.5.0 des Adapters?

**Comment by mcm1957** [comment]
In enen diesem repository.

Musst dir halt aus der history den passenden Stand / commit suchen wenn es kein Tag gibt.

Tags sind nicht verpflichtend. Ist zwar gutePraxis aber niemand kann einen dev zwingen saubere Tags zu setzen.

**Comment by marian-t-web-de** [comment]
Es geht nicht um mich. Sollte der unwahrscheinlicher Fall auftreten, dass sich jemand findet, der den Bug ausbügeln würde dann hilft Ihm die Version auf meinem Raspi wenig. Außerdem ist Github dafür da dass die Versionen immer nachvollziehbar abgelegt werden sein sollen und sich nicht einfach in der Luft auflösen.

Kannst du ggfs. ein Screenshot einfügen wie ich die fehlende Version in Github suchen soll?

**Comment by mcm1957** [comment]
Zitat:
> Musst dir halt aus der history den passenden Stand / commit suchen wenn es kein Tag gibt.

Wenn die Version vor Jahren nicht getagged wurde kannst du sie nicht über ein Tag bzw. über eine Versionsnummer finden. GitHub hat aber wie du richtigs chreibst alle Änderungen in Form der Commit History gespeichert. Welchen Stand ein User vor Jahren auf npm gepushed hat ist mir nicht bekannt. Wie beschreits geschrieben kannst du nur die Änderungen auf GitHub durchsehen.

Hier siehst du alle Änderungen zurück bis zum Urknall:
![image](https://github.com/user-attachments/assets/887a7d4b-d370-4ca5-80e2-513532bb819b)

**Comment by marian-t-web-de** [comment]
Ich habe die noch vorhandenen Versionen nacheinander installiert und getestet. Die ver. 0.5.1 bis 0.5.7 funktionieren mit SamsugHJ API, die 0.5.8 und spätere nicht. Ich versuche noch die Änderungen zw. v.0.5.7 und 0.5.8 einzeln zu Analysieren

Die ausgelieferte v.0.5.7 ist ein Sonderfall, produziert laute Fehler(??):
`<html>
<body>

host.iobroker | 2024-08-26 10:09:38.075 | info | Do not restart adapter system.adapter.samsung.0 because disabled or deleted
-- | -- | -- | --
host.iobroker | 2024-08-26 10:09:38.074 | error | instance system.adapter.samsung.0 terminated with code 3 (NO_ADAPTER_CONFIG_FOUND)
samsung.0 | 2024-08-26 10:09:37.399 | warn | Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
samsung.0 | 2024-08-26 10:09:37.398 | debug | Plugin sentry destroyed
samsung.0 | 2024-08-26 10:09:37.339 | error | adapter disabled
samsung.0 | 2024-08-26 10:09:37.002 | debug | Plugin sentry Initialize Plugin (enabled=true)
host.iobroker | 2024-08-26 10:09:11.214 | info | "system.adapter.samsung.0" disabled
host.iobroker | 2024-08-26 10:09:04.131 | info | Restart adapter system.adapter.samsung.0 because enabled
host.iobroker | 2024-08-26 10:09:04.131 | error | instance system.adapter.samsung.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker | 2024-08-26 10:09:04.130 | error | Caught by controller[0]: at addChunk (node:internal/streams/readable:368:12)
host.iobroker | 2024-08-26 10:09:04.130 | error | Caught by controller[0]: at Socket.emit (node:domain:489:12)
host.iobroker | 2024-08-26 10:09:04.130 | error | Caught by controller[0]: at Socket.emit (node:events:517:28)
host.iobroker | 2024-08-26 10:09:04.130 | error | Caught by controller[0]: at Socket.socketOnData (/opt/iobroker/node_modules/ws/lib/websocket.js:1355:35)
host.iobroker | 2024-08-26 10:09:04.130 | error | Caught by controller[0]: at Receiver.Writable.write (node:internal/streams/writable:337:10)
host.iobroker | 2024-08-26 10:09:04.130 | error | Caught by controller[0]: at _write (node:internal/streams/writable:333:10)
host.iobroker | 2024-08-26 10:09:04.130 | error | Caught by controller[0]: at writeOrBuffer (node:internal/streams/writable:392:12)
host.iobroker | 2024-08-26 10:09:04.130 | error | Caught by controller[0]: at Receiver._write (/opt/iobroker/node_modules/ws/lib/receiver.js:94:10)
host.iobroker | 2024-08-26 10:09:04.130 | error | Caught by controller[0]: at Receiver.startLoop (/opt/iobroker/node_modules/ws/lib/receiver.js:167:16)
host.iobroker | 2024-08-26 10:09:04.130 | error | Caught by controller[0]: at Receiver.getData (/opt/iobroker/node_modules/ws/lib/receiver.js:496:10)
host.iobroker | 2024-08-26 10:09:04.129 | error | Caught by controller[0]: at Receiver.dataMessage (/opt/iobroker/node_modules/ws/lib/receiver.js:596:14)
host.iobroker | 2024-08-26 10:09:04.129 | error | Caught by controller[0]: at Receiver.emit (node:domain:489:12)
host.iobroker | 2024-08-26 10:09:04.129 | error | Caught by controller[0]: at Receiver.emit (node:events:517:28)
host.iobroker | 2024-08-26 10:09:04.129 | error | Caught by controller[0]: at Receiver.receiverOnMessage (/opt/iobroker/node_modules/ws/lib/websocket.js:1220:20)
host.iobroker | 2024-08-26 10:09:04.129 | error | Caught by controller[0]: at WebSocket.emit (node:domain:489:12)
host.iobroker | 2024-08-26 10:09:04.129 | error | Caught by controller[0]: at WebSocket.emit (node:events:517:28)
host.iobroker | 2024-08-26 10:09:04.129 | error | Caught by controller[0]: at WebSocket.<anonymous> (/opt/iobroker/node_modules/iobroker.samsung/lib/H-and-J-Series-lib/Connection/SamsungTvConnection.js:108:9)
host.iobroker | 2024-08-26 10:09:04.129 | error | Caught by controller[0]: at onMessageEmitter (/opt/iobroker/node_modules/iobroker.samsung/lib/H-and-J-Series-lib/Connection/SamsungTvConnection.js:148:12)
host.iobroker | 2024-08-26 10:09:04.129 | error | Caught by controller[0]: at Messages.handle (/opt/iobroker/node_modules/iobroker.samsung/lib/H-and-J-Series-lib/Connection/Messages.js:19:38)
host.iobroker | 2024-08-26 10:09:04.128 | error | Caught by controller[0]: at Array.find (<anonymous>)
host.iobroker | 2024-08-26 10:09:04.128 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.samsung/lib/H-and-J-Series-lib/Connection/Messages.js:19:76
host.iobroker | 2024-08-26 10:09:04.128 | error | Caught by controller[0]: at Object.messages.on.socket.socket [as matcher] (/opt/iobroker/node_modules/iobroker.samsung/lib/H-and-J-Series-lib/Connection/SamsungTvConnection.js:62:26)
host.iobroker | 2024-08-26 10:09:04.127 | error | Caught by controller[0]: TypeError: data.startsWith is not a function
samsung.0 | 2024-08-26 10:09:03.576 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
samsung.0 | 2024-08-26 10:09:03.575 | debug | Plugin sentry destroyed
samsung.0 | 2024-08-26 10:09:03.574 | info | terminating
samsung.0 | 2024-08-26 10:09:03.544 | error | data.startsWith is not a function
samsung.0 | 2024-08-26 10:09:03.543 | error | TypeError: data.startsWith is not a function at Object.messages.on.socket.socket [as matcher] (/opt/iobroker/node_modules/iobroker.samsung/lib/H-and-J-Series-lib/Connection/SamsungTvConnection.js:62:26) at /opt/iobroker/node_modules/iobroker.samsung/lib/H-and-J-Series-lib/Connection/Messages.js:19:76 at Array.find (<anonymous>) at Messages.handle (/opt/iobroker/node_modules/iobroker.samsung/lib/H-and-J-Series-lib/Connection/Messages.js:19:38) at onMessageEmitter (/opt/iobroker/node_modules/iobroker.samsung/lib/H-and-J-Series-lib/Connection/SamsungTvConnection.js:148:12) at WebSocket.<anonymous> (/opt/iobroker/node_modules/iobroker.samsung/lib/H-and-J-Series-lib/Connection/SamsungTvConnection.js:108:9) at WebSocket.emit (node:events:517:28) at WebSocket.emit (node:domain:489:12) at Receiver.receiverOnMessage (/opt/iobroker/node_modules/ws/lib/websocket.js:1220:20) at Receiver.emit (node:events:517:28) at Receiver.emit (node:domain:489:12) at Receiver.dataMessage (/opt/iobroker/node_modules/ws/lib/receiver.js:596:14) at Receiver.getData (/opt/iobroker/node_modules/ws/lib/receiver.js:496:10) at Receiver.startLoop (/opt/iobroker/node_modules/ws/lib/receiver.js:167:16) at Receiver._write (/opt/iobroker/node_modules/ws/lib/receiver.js:94:10) at writeOrBuffer (node:internal/streams/writable:392:12) at _write (node:internal/streams/writable:333:10) at Receiver.Writable.write (node:internal/streams/writable:337:10) at Socket.socketOnData (/opt/iobroker/node_modules/ws/lib/websocket.js:1355:35) at Socket.emit (node:events:517:28) at Socket.emit (node:domain:489:12) at addChunk (node:internal/streams/readable:368:12)
samsung.0 | 2024-08-26 10:09:03.543 | error | uncaught exception: data.startsWith is not a function
samsung.0 | 2024-08-26 10:09:02.810 | info | Connection to TV initialised
samsung.0 | 2024-08-26 10:09:02.809 | debug | resp is init2 all is done
samsung.0 | 2024-08-26 10:09:02.749 | debug | Initializing HJ lib
samsung.0 | 2024-08-26 10:09:02.727 | info | starting. Version 0.5.7 in /opt/iobroker/node_modules/iobroker.samsung, node: v18.19.0, js-controller: 5.0.19


</body>
</html>`

**Comment by marian-t-web-de** [comment]
04.09.2024 Ergänzung in post mit [analyse](https://github.com/iobroker-community-adapters/ioBroker.samsung/issues/202#issuecomment-2304226880) oben, weil dazugehört

**Comment by mcm1957** [comment]
Dev Remark:

Versionen kleiner 0.6.0 sind nicht mit js-controller 6 und neuer kompatibel da diese noch keine aktuelle Version v Adapter Core verwenden.

**Comment by marian-t-web-de** [comment]
@mcm1957 
Habe endlich den bug gefixed!!! :-) 

Lag an einem anderen Format der Messeages aus dem WebSocket, was im Adapter einer anderen Behandlung erfordert.

Frage mich wie ich es veröffentlichen kann. Einen GitHub User/Projekt habe ich, muss ich noch lernen wie ich ein Pull Request für ver.0.6.1 hinkriege.

**Comment by marian-t-web-de** [comment]
@mcm1957 
Habe endlich den bug gefixed!!! :-) 

Lag an einem anderem Format der Messeages aus dem WebSocket, was im Adapter einer anderen Behandlung erfordert.

Frage mich wie ich es veröffenlichen kann. Einen GitHub User/Projekt habe ich, muss ich noch lernen wie ich ein Pull Request für ver.0.6.1 hinkriege.

**Comment by Apollon77** [comment]
Also im einfachsten Fall einfach die GitHub Web UI nutzen. lso das betroffenen File mit stift editieren und ändern... dann runter scrollen dann machst du einen Commit und auf der nächsten Seite kannst DU Pull Request anlegen. Wenn es mehrere änderungen sind dann nach der ersten und PR erstellung oben schauen, da ist der Branch name von deinem Fork angegeben und klicklen. Dort weitere änderungen achen die werden dann da hinzugefügt

**Comment by mcm1957** [comment]
ÐANKE.

Wenn du eine Fork des Adapter Repos hast dann einfach die Änderung in deinem Fork einchecken. Anschließend in GH Webseite bei deinen Fork CONTRIBUTE oder so ähnlich anklicken. Sollte eine PR erstellen.

Bin noch bis zum WE auf Urlaub u kann nur via Handy antworten. Sorry.

Ansonsten frag noch mal im Forum oder Ping @Apillon77 an. Oder meld dichbin ioBroker Zelegramm Dev Gruppen. Invites auf www.iobroker.dev

**Comment by mcm1957** [comment]
fixed at 0.6.1

**Comment by mcm1957** [comment]
@marian-t-web-de 
Please retest with 0.6.1
