### ISSUE TITLE
Not able to select HMDI3 as Input Source

### ISSUE THREAD

**Issue by OneCreek** [iobroker-community-adapters/ioBroker.samsung#219]
After [marian-t-web-de] (updated) (https://github.com/mcm1957) fixed #138 after a very long time of waiting (big thanks for that!), turning off and menu navigation works now with my SamsungHJ with model 2015: UE55ju6850.

What's not working is turning the TV on (which might be hardware related?) and choosing HMDI3 as imput source. #
.       samsung.1.Input.Source
.       samsung.1.Input.TV
.       samsung.1.Input.Contents
.       samsung.1.Volume.xxx
.       samsung.1.Navigation.xxx
-> Buttons all work
.       samsung.1.Input.HDMI3
-> Button doesn't work somehow... No reaction. 

**Describe the bug**  
Nothing happens. 

**To Reproduce**  
Modus API: SamsungHJ (for UE55ju6850)
Pressing Button in objects: samsung.1.Input.HDMI3
What works:... samsung.1.Input.Source, samsung.1.Navigation.Right, samsung.1.Navigation.Right, samsung.1.Navigation.Enter
which is a really bad workaround :D

**Expected behavior**  
TV should change to source HDMI3

**Screenshots & Logfiles**  
```
19:20:11.962 | debug | stateChange  samsung.1.Input.HDMI3 =  {"val":false,"ack":true,"ts":1727630411957,"q":0,"from":"system.adapter.samsung.1","user":"system.user.admin","lc":1727630411957}
19:20:11.909 | debug | Executing command: KEY_HDMI3
19:20:11.904 | debug | stateChange  samsung.1.Input.HDMI3 =  {"val":true,"ack":false,"ts":1727630411901,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1727630411901}
```

**Versions:**  
 - Adapter version: 0.6.1
 - JS-Controller version: 6.0.11
 - Node version: v20.17.0
 - NMP: 10.8.2
 - Operating system: ubuntu with docker (official image - v10.0.0)

**Comment by mcm1957** [comment]
Important correction:
I did NOT fix the problems, **All code changes have been investigated and provided by @marian-t-web-de. Please address Thanls to him.** He did a good job although I (and others) did mot have time and equipment to support him.

**Comment by mcm1957** [comment]
@OneCreek 
Please specify / confirm API selection. I assume you have configutred "SamsungHJ".

**Comment by OneCreek** [comment]
> @OneCreek 
> Please specify / confirm API selection. I assume you have configutred "SamsungHJ".

Yes, sorry for missing out on that detail. 
SamsungHJ with IP address, Pin (and Mac address) fields filled out.

**Comment by marian-t-web-de** [comment]
Hello,
all changes I've provided are SamsungHJ relevant - see code.

MfG
Marian T.
Von Samsung Galaxy gesendet.

-----Original Message-----

**Comment by marian-t-web-de** [comment]
There is no HDMI Problem. The KEY-list is a merge of Samsung-TV's produced btw. about 2010-2018.
My TV, model UE55JS8590 also cannot be switched to HDMI neither via remote nor via Smart-App or ioB-Adapter.
It is by this model only via Source meue working.  Unfortunately, which Keys are by Your TV working can You try yourself only.
Also I cannot switch my TV On via Adapter, the reason see answer before.

Moreover, the Keys In ioBroker Adapter are send 1:1 to the TV, there is no function to check which one is working. I'm not shure if we get an error from TV by wrong Key, if yes, maybe one of the creators of this Adapter could implement it. For me no reaction on TV is actually enough.

Remark: all this has nothing together with the actuall changes.

**Comment by mcm1957** [comment]
I do not think that the problem has anything to do with your changes.
I only asked you to do a review if you can detect the source for the problem. It's clear that some TVs cannot be controlled. But its very unlikely that switching to HMS 1, 2 and 4 works for a unit but hdmi 3 does not :-). For this behavior a problem in the adapter is much more likely.

But its ok if you do not want to spend time. Anway THANKS for the fixes you provided already

**Comment by mcm1957** [comment]
@OneCreek 
As you did not state at this issue (but I think you did at forum) let me ask :

- samsung.1.Input.HDMI3 - button does not work

-. samsung.1.Input.HDMI1 / 2 / 4 - do those buttons work or does none of these buttons work ?

**Comment by marian-t-web-de** [comment]
@OneCreek 
one more question from me: KEY_HDMI1 seems not to be implemented in the SP-object states, there is KEY_HDMI only. How du You set it?

With my TV model are  keys KEY_HDMI1 till -4 defitely not working. But... KEY_HDMI switches to  HDMI2.
It is surely  not self-explaining :-(

**Comment by OneCreek** [comment]
> @OneCreek As you did not state at this issue (but I think you did at forum) let me ask :
> -. samsung.1.Input.HDMI1 / 2 / 4 - do those buttons work or does none of these buttons work ?

None of these work. Sorry for the confusion. 
So I think it's a TV Issue and the issue can be closed...
Thanks for clarifying anyhow!

**Comment by OneCreek** [comment]
> @OneCreek As you did not state at this issue (but I think you did at forum) let me ask :
> -. samsung.1.Input.HDMI1 / 2 / 4 - do those buttons work or does none of these buttons work ?

None of these work. Sorry for the confusion. 
So I think it's a TV Issue and the issue can be closed...
Thanks for clarifying anyhow!

**Comment by marian-t-web-de** [comment]
@mcm1957 
maybe we should change the HDMI SP/KEY_HDMI to HDMI1 SP/KEY_HDMI1 ( or add the second) - for TV models with which it is working?
But I cannot test it.

**Comment by OneCreek** [comment]
> @mcm1957 maybe we should change the HDMI SP/KEY_HDMI to HDMI1 SP/KEY_HDMI1 ( or add the second) - for TV models with which it is working? But I cannot test it.

I just checked with my TV. `samsung.1.Input.HDMI` button works and changes to HDMI1.
