### ISSUE TITLE
Warnung im Log State "samsung-community.0.Power.on" has no existing object

### ISSUE THREAD

**Issue by marian-t-web-de** [iobroker-community-adapters/ioBroker.samsung#71]
Zuerst **einen herzlichen DANK** für die Implementierung der SamsungHJ API, funktioniert bei mit mit UE55JS8590TXZG aus dem Jahr 2015 sehr gut.

Im Log erscheint eine Warnung "2021-09-14 23:07:11.324 - warn: samsung-community.0 (10046) State "samsung-community.0.Power.on" has no existing object, this might lead to an error in future versions".

State "samsung-community.0.Power.on" wird in main.js verwendet, zumindest bei APIType SamsungHJ wird aber nicht als State angelegt, da bei SamsungHJ ohnehin ohne Funktion.

Vielleicht wäre am einfachsten den State bei Instanziierung anzulegen.

Samsung-Fernseher Adapter ist in ver. 0.5.0, der Rest (Node.jsv12.22.0 NPM 6.4.11) scheint mir hier irrelevant.

Es ist kein hohes Prio, daher wäre nett das bei der nächsten Gelegenheit zu bereinigen.

Vielen Dank in Voraus.

**Comment by marian-t-web-de** [comment]
Hallo,
Also ist nicht gelöst und wird geschlossen?
MfG
M. Tkocz

MfG
Marian T.
Von Samsung Galaxy gesendet.

-----Original Message-----

**Comment by Apollon77** [comment]
No .. because you said that it is still open. Then stalebot will not close it

**Comment by Apollon77** [comment]
Fixed on Github
